### ISSUE TITLE
admission-alicloud depends on the Alicloud API

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-alicloud#489]
/area high-availability
/area robustness
/kind bug
/platform alicloud

**What happened**:
With https://github.com/gardener/gardener-extension-provider-alicloud/pull/443 the following handling is added to the Shoot validator:
https://github.com/gardener/gardener-extension-provider-alicloud/blob/b823ea14db3e132b6ae7500321a6ebe3e9553f7d/pkg/admission/validator/shoot.go#L214-L246

It means that for every Shoot create/update request we call the Alicloud API. We, usually, avoid such dependencies to external systems in the provider admission components as it means that if the request to the Alicloud API fails for some reason it is no longer possible to create/update Shoots on our side.

**What you expected to happen**:
No validation that depends on the availability of the Alicloud API to exist in the Shoot validator. Instead another validation mechanism to be used - for example Infrastructure [`ConfigValidator`](https://github.com/stoyanr/gardener/blob/aa9b526a872f1c5894083f72a519042ed829839a/docs/extensions/infrastructure.md#configvalidator-interface) (ref https://github.com/gardener/gardener-extension-provider-aws/pull/403).

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.36.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by shafeeqes** [comment]
This issue also turns the [Shoot Force Deletion](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#force-deletion) unusable.
The deletion is rejected, even though the webhook is not acting on DELETE,

https://github.com/gardener/gardener-extension-provider-alicloud/blob/3c439a2c1c9d6766d74a4788635e713a0b65ed10/charts/gardener-extension-admission-alicloud/charts/application/templates/validatingwebhook-validator.yaml#L14-L15

but the addition of `confirmation.gardener.cloud/deletion` also triggers it and it fails because of invalid credentials, which means a Shoot with invalid credentials can never be deleted in the first place.

Either we should address the current issue in hand or workaround for now by ignoring annotation updates.

**Comment by shafeeqes** [comment]
/close
Ref https://github.com/gardener/gardener-extension-provider-alicloud/pull/681#issuecomment-1886361123
